export function normalizeText(text) {
    return text.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();
}

export function tokenize(text) {
    const stopwords = new Set(["the", "a", "is", "and", "to", "in", "of"]);
    return new Set(text.split(/\s+/).filter(word => !stopwords.has(word)));
}

export function parseISO8601Duration(duration) {
    const regex = /PT(?:(\d+)M)?(?:(\d+)S)?/;
    const matches = duration.match(regex);
  
    const minutes = parseInt(matches[1] || "0", 10);
    const seconds = parseInt(matches[2] || "0", 10);
  
    return minutes * 60 + seconds;
}

function scoreDuration(video, track) {
    const durationDiff = Math.abs(video.seconds - Math.round(track.duration_ms) / 1000);
    if (Math.floor(durationDiff) <= 5) return 2;
    if (Math.floor(durationDiff) <= 20) return 0;
    return -2;
}

function scoreKeywords(text, keywords, weight = 1) {
    return Array.from(keywords).reduce((score, keyword) => {
      if (text.includes(keyword)) score += weight;
      return score;
    }, 0);
    
}
  
function scoreNegativeKeywords(text, keywords, weight = -2) {
    return Array.from(keywords).reduce((score, keyword) => {
      if (text.includes(keyword)) score += weight;
      return score;
    }, 0);
}

export function parseVideoTitle(videoTitle) {
    const stopwords = [
      "official video", "official audio", "official", "remix", "new song",
      "live", "music video", "performance", "feat.", "ft.", "featuring",
      "lyric video", "lyrics video", "with lyrics", "lyrics", "hq", "hd",
       "()"
    ];
  
    let cleanTitle = videoTitle.toLowerCase()
      .replace(/[\[\]\(\)\|]/g, '')
      .replace(/[^a-z0-9\s\-]/g, '')
      .trim();
  
    stopwords.forEach(word => {
      const regex = new RegExp(`\\b${word}\\b`, 'gi');
      cleanTitle = cleanTitle.replace(regex, '');
    });

    const parts = cleanTitle.split(/[-|]/).map(part => part.trim());

    if (parts.length < 2) {
      return cleanTitle;
    }
  
    const artist = parts[0];
    const song = parts.slice(1).join(' - ');
  
    return `${artist} ${song}`;
  
  }
  

export async function scoreTrack(spotifyTrack, videoMetadata) {
    let scoreDetails = {
        duration: 0,
        positiveKeywords: 0,
        negativeKeywords: 0,
        negativeNamewords: 0,
        authorMatch: 0,
        autoGenerated: 0,
        bonus: 0
    };

    const trackName = normalizeText(spotifyTrack.name);
    const trackArtists = spotifyTrack.artists.map(artist => normalizeText(artist.name));
    const trackAlbum = normalizeText(spotifyTrack.album.name);

    const positiveKeywords = new Set([trackName, ...trackArtists, trackAlbum, "official"]);
    const negativeNamewords = new Set(["instrumental", "cover", "remix", "live", "acoustic", "reupload", "playtrough"]);
    const negativeKeywords = new Set(["tutorial", "how to", "fair use", "copyright", "subs", "sub", "fan", "disclaimer"]);

    const videoTitle = normalizeText(videoMetadata.title);
    const videoDescription = normalizeText(videoMetadata.description);

    if (Math.abs(videoMetadata.seconds - Math.round(spotifyTrack.duration_ms) / 1000) >=30) {
        // console.log(`Duration mismatch for ${videoMetadata.title} - ${videoMetadata.url} and ${trackName} - ${spotifyTrack.external_urls.spotify}`);
        return null;
    }

    scoreDetails.duration = scoreDuration(videoMetadata, spotifyTrack);

    scoreDetails.positiveKeywords += scoreKeywords(videoTitle, positiveKeywords, 2);
    scoreDetails.positiveKeywords += scoreKeywords(videoDescription, positiveKeywords, 1);

    scoreDetails.negativeKeywords += scoreNegativeKeywords(videoTitle, negativeKeywords, -2);
    scoreDetails.negativeKeywords += scoreNegativeKeywords(videoDescription, negativeKeywords, -1);

    for (const keyword of negativeNamewords) {
        if (videoTitle.includes(keyword) && !trackName.includes(keyword) || !videoTitle.includes(keyword) && trackName.includes(keyword)) {
        scoreDetails.negativeNamewords -= 3;
        } else if (videoTitle.includes(keyword) && trackName.includes(keyword)) {
        scoreDetails.negativeNamewords += 2;
        }
    }

    for (const artist of trackArtists) {
        if (normalizeText(videoMetadata.author.name).includes(artist)) {
        scoreDetails.authorMatch += 2;
        }
        if (videoDescription.includes("autogenerated by youtube") && videoDescription.includes(artist)) {
        scoreDetails.authorMatch++;
        }
    }

    if (videoDescription.includes("autogenerated by youtube") && videoDescription.includes(`${trackName} ·`)) {
        scoreDetails.autoGenerated++;
    }
    if (videoDescription.includes("autogenerated by youtube") && videoDescription.includes(trackAlbum)) {
        scoreDetails.autoGenerated++;
    }

    return scoreDetails;
}
